apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8017 # Container port
  type: LoadBalancer
